---
- name: get all_hosts
  set_fact:
    all_hosts: "{{ unbound_conf_file | get_all_hosts }}"

- name: install pexpect
  pip:
    name: pexpect
  become: yes
  become_user: root
  delegate_to: "{{ item }}"
  with_items: "{{ all_hosts }}"

- name: Install expect packages for atlas
  package:
    name: expect
    state: present
  become: yes
  become_user: root
  delegate_to: "{{ item }}"
  with_items: "{{ all_hosts }}"

- name: copy password_gen
  template:
    src: password_gen.j2
    dest: /etc/atlas/conf/password_gen
    mode: 0755
  become: yes
  become_user: root

- name: Execute the script
  command: /etc/atlas/conf/password_gen
  become: yes
  become_user: root

- name: Set right permission for atlas jceks files
  file:
    path: "{{ item }}"
    mode: 0444
    owner: atlas
    group: hadoop
  loop:
    - "{{ passwdFileLocationActualPath }}"
    - "{{ passwdCrcFileLocation }}"
  become: yes
  become_user: root

- name: Save SSL configs for Atlas
  include_role:
    name: ambari_configure_service
  vars:
    ambari_component_section_name: "{{ atlas_application_properties_config_type }}"
    ambari_component_props: "{{ atlas_application_properties_config_props }}"

- name: Save SSL configs for Atlas-Ranger Plugin
  include_role:
    name: ambari_configure_service
  vars:
    ambari_component_section_name: "{{ atlas_ranger_plugin_config_type }}"
    ambari_component_props: "{{ atlas_ranger_plugin_config_props }}"
