---
- set_fact:
    ansible_python_default_interpreter: "{{ ansible_python_interpreter }}"
    ansible_python_interpreter:  "/usr/bin/python"

- name: set_fact
  set_fact:
    all_hosts: "{{ groups['OOZIE_SERVER'] }}"

- name: Read all hosts and set it with index
  set_fact:
    oozie_host_{{ item.0 }} : "{{ item.1 }}"
  with_indexed_items: "{{ all_hosts }}"

- name: Install apache server packages
  package:
    name: "{{ webserver_service }}"
    state: present
  become: yes
  become_user: root

- name: Creates sites-available directory
  file:
    path: /etc/{{ webserver_service }}/sites-available
    state: directory
    mode: 0777
  become: yes
  become_user: root

- name: Creates sites-enabled directory
  file:
    path: /etc/{{ webserver_service }}/sites-enabled
    state: directory
    mode: 0777
  become: yes
  become_user: root

- name: create virtual host file
  template: src="oozie_loadbalancer.conf.j2" dest="/etc/{{ webserver_service }}/sites-available/{{ domain }}.conf"
  become: yes
  become_user: root

- name: create symlinks to enabled virtual hosts
  file:
    src: "/etc/{{ webserver_service }}/sites-available/{{ domain }}.conf"
    dest: "/etc/{{ webserver_service }}/sites-enabled/{{ domain }}.conf"
    state: link

- name: Append conf in httpd.conf file
  become: yes
  become_user: root
  lineinfile:
    path: "/etc/{{ webserver_service }}/conf/{{ webserver_service }}.conf"
    line: IncludeOptional sites-enabled/*.conf
  notify:
    - restart {{ webserver_service }}